# indicating which version of Docker-compose we wish to use
version: '3.7'

services:
  back:
    build: ./back
    image:
      # name of the image which is used for the current service
      custom/back
    # naming our resulting container
    container_name: back
    ports:
      - '5000:5000'

  front:
    build: ./front
    image:
      custom/front
    container_name: front
    ports:
      - '3333:80'

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - '5433:5432'
    volumes:
      # copy the sql script to create tables
      - ./db:/docker-entrypoint-initdb.d/
      - disp-db-volume:/var/lib/postgres/data

volumes:
  disp-db-volume:
    external: false